from setuptools import setup, find_packages

setup(
    name="youtube_semantic_segmenter",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "streamlit>=1.32.0",
        "plotly>=5.19.0",
        "pandas>=2.2.1",
        "numpy>=1.26.4",
        "openai-whisper>=20231117",
        "pytube>=15.0.0",
        "pydub>=0.25.1",
        "torch>=2.2.1",
        "torchaudio>=2.2.1",
        "transformers>=4.38.2",
        "ffmpeg-python>=0.2.0",
        "python-dotenv>=1.0.1",
        "scikit-learn>=1.4.1.post1",
        "librosa>=0.10.1",
        "soundfile>=0.12.1",
        "yt-dlp>=2024.3.10",
    ],
    author="Achal Bajpai",
    author_email="achalbajpai@gmail.com",
    description="A tool that segments YouTube videos into semantically meaningful chunks with transcripts",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/achalbajpai/youtube-semantic-segmenter",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
    ],
    python_requires=">=3.9",
)
